[versions]
junit = "5.11.4"

[libraries]
javalin = { module= "io.javalin:javalin-bundle", version = "6.7.0" }
jena = { module = "org.apache.jena:apache-jena-libs", version = "4.10.0" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
wldt = { module = "io.github.wldt:wldt-core", version = "0.3.0" }
wot-servient = { module = "io.github.sane-city:wot-servient", version = "1.16-SNAPSHOT" }

[bundles]
java-testing = [ "junit-api" ]

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "5.1.8" }
java-qa = { id = "org.danilopianini.gradle-java-qa", version = "1.57.1"}
publish-on-central = { id = "org.danilopianini.publish-on-central", version = "9.1.10" }
